### PR TITLE
Remove large sqlite files

### PR DESCRIPTION
**Pull request by gwaybio**
These large files makes working with this repo quite difficult. Let's remove them :)

### CODE REVIEW

**Comment by gwaybio** [comment]
Can we add them to a **dedicated** folder (alongside the processed features you sent yesterday) on dropbox?

**Review by jenna-tomkinson — COMMENTED** [review]
Can you also remove the Wave 2 sqlite file as well in this PR?

Then it will LGTM! I will send you the link to the folder for all the Interstellar sqlite files.

**Comment by jenna-tomkinson** [comment]
@gwaybio 

Are you still able to complete this PR?

**Comment by jenna-tomkinson** [comment]
@gwaybio 

I'll just close it and make this change in my new PR for editing the wave 1 modules.

**Pull request closed without merging**
